// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ManytomanyUserAgendasFluentApi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManytomanyUserAgendasFluentApi));
        
        string IMigrationMetadata.Id
        {
            get { return "201811011237573_Many to many User-Agendas-FluentApi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
